---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gardener.cloud:system:gardener-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: gardener
    role: operator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - secrets
  - serviceaccounts
  - services
  - services/status
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - verticalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - resources.gardener.cloud
  resources:
  - managedresources
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - bind
  - escalate
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - gardener-operator-leader-election
  verbs:
  - update
- apiGroups:
  - druid.gardener.cloud
  resources:
  - etcds
  - etcdcopybackupstasks
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - hvpas
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - hvpas
  resourceNames:
  - virtual-garden-etcd-events
  - virtual-garden-etcd-main
  verbs:
  - delete
  - patch
  - update
