trustDomain: cluster.local
image: to-be-injected-by-imagevector
labels:
  app: istiod
  istio: pilot
deployNamespace: false
ports:
  https: 10250
portsNames:
  metrics: metrics
serviceName: istiod

# TODO(timuthy): To be removed in a future release. Only required to move objects to a new ManagedResource.
ignoreMode: false
