{
 "title": "Node/Worker Pool Overview",
 "tags": [
  "workload",
  "shoot"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "worker_group",
    "label": "Worker Group",
    "query": {
     "query": "label_values(kube_node_labels, label_worker_gardener_cloud_pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average CPU Usage of Nodes in Worker Group(s) $worker_group",
   "type": "graph",
   "description": "Shows the average CPU usage of all nodes in the selected worker group(s).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "avg by (label_worker_gardener_cloud_pool) (\n    sum by (node) (rate(node_cpu_seconds_total{mode=~\"system|user|irq|softirq\"}[$__rate_interval]))\n  + on (node) group_right ()\n    sum by (label_worker_gardener_cloud_pool, node) (\n      0 * kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"}\n    )\n)",
     "legendFormat": "{{label_worker_gardener_cloud_pool}}"
    }
   ]
  },
  {
   "title": "Average Memory Usage of Nodes in Worker Group(s) $worker_group",
   "type": "graph",
   "description": "Shows the memory usage of all nodes in the selected worker group(s).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "avg by (label_worker_gardener_cloud_pool) (\n    sum by (node) (node_memory_Active_bytes)\n  + on (node) group_right ()\n    sum by (label_worker_gardener_cloud_pool, node) (\n      0 * kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"}\n    )\n)",
     "legendFormat": "{{label_worker_gardener_cloud_pool}}"
    }
   ]
  },
  {
   "title": "Average CPU Utilization of Nodes in Worker Group(s) $worker_group",
   "type": "graph",
   "description": "Shows the average CPU utilization of all nodes in the selected worker group(s).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Percentile" }
   ],
   "targets": [
    {
     "expr": "avg by (label_worker_gardener_cloud_pool) (\n        sum by (node) (rate(node_cpu_seconds_total{mode=~\"system|user|irq|softirq\"}[$__rate_interval]))\n      /\n        sum by (node) (kube_node_status_capacity{resource=\"cpu\",unit=\"core\"})\n    *\n      100\n  + on (node) group_right ()\n    sum by (label_worker_gardener_cloud_pool, node) (\n      0 * kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"}\n    )\n)",
     "legendFormat": "{{label_worker_gardener_cloud_pool}}"
    }
   ]
  },
  {
   "title": "Average Memory Utilization of Nodes in Worker Group(s) $worker_group",
   "type": "graph",
   "description": "Shows the average memory utilization of all nodes in the selected worker group(s).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Percentile" }
   ],
   "targets": [
    {
     "expr": "avg by (label_worker_gardener_cloud_pool) (\n      sum by (node) (\n        (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes\n      )\n    *\n      100\n  + on (node) group_right ()\n    sum by (label_worker_gardener_cloud_pool, node) (\n      0 * kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"}\n    )\n)",
     "legendFormat": "{{label_worker_gardener_cloud_pool}}"
    }
   ]
  },
  {
   "title": "Number of Nodes in Worker Group(s) $worker_group",
   "type": "graph",
   "description": "Shows the number of nodes of selected worker groups in the cluster over time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"}) by (label_worker_gardener_cloud_pool)",
     "legendFormat": "{{label_worker_gardener_cloud_pool}}"
    },
    {
     "expr": "count(kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"})",
     "legendFormat": "Sum of selected groups"
    }
   ]
  },
  {
   "title": "Average # of Pods on each Node in Worker Group(s) $worker_group",
   "type": "graph",
   "description": "Shows the average number of pods running on each node of the selected worker group(s).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Pods" }
   ],
   "targets": [
    {
     "expr": "avg by (label_worker_gardener_cloud_pool) (\n    sum by (node) (\n      label_replace(\n        sum by (kubernetes_io_hostname) (kubelet_running_pods),\n        \"node\",\n        \"$1\",\n        \"kubernetes_io_hostname\",\n        \"(.+)\"\n      )\n    )\n  + on (node) group_right ()\n    sum by (label_worker_gardener_cloud_pool, node) (\n      0 * kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"}\n    )\n)",
     "legendFormat": "{{label_worker_gardener_cloud_pool}}"
    }
   ]
  },
  {
   "title": "Overview of all Nodes",
   "type": "table-old",
   "description": "Shows an overview of all nodes in the shoot cluster.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "  sum by (node) (rate(node_cpu_seconds_total{mode=~\"system|user|irq|softirq\"}[$__rate_interval]))\n+ on (node) group_right ()\n  sum by (label_worker_gardener_cloud_pool, node) (\n    0 * kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"}\n  )"
    },
    {
     "expr": "  sum by (node) (kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"})\n+ on (node) group_right ()\n  sum by (label_worker_gardener_cloud_pool, node) (\n    0 * kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"}\n  )"
    },
    {
     "expr": "  (\n      sum by (node) (kube_node_status_allocatable{resource=\"cpu\",unit=\"core\"})\n    -\n      sum by (node) (rate(node_cpu_seconds_total{mode=~\"system|user|irq|softirq\"}[$__rate_interval]))\n  )\n+ on (node) group_right ()\n  sum by (label_worker_gardener_cloud_pool, node) (\n    0 * kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"}\n  )"
    },
    {
     "expr": "  sum by (node) (node_memory_Active_bytes)\n+ on (node) group_right ()\n  sum by (label_worker_gardener_cloud_pool, node) (\n    0 * kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"}\n  )"
    },
    {
     "expr": "  sum by (node) (kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"})\n+ on (node) group_right ()\n  sum by (label_worker_gardener_cloud_pool, node) (\n    0 * kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"}\n  )"
    },
    {
     "expr": "  (\n      sum by (node) (kube_node_status_allocatable{resource=\"memory\",unit=\"byte\"})\n    -\n      sum by (node) (node_memory_Active_bytes)\n  )\n+ on (node) group_right ()\n  sum by (label_worker_gardener_cloud_pool, node) (\n    0 * kube_node_labels{label_worker_gardener_cloud_pool=~\"$worker_group\"}\n  )"
    },
    {
     "expr": "sum without (kubernetes_io_hostname) (\n  label_replace(\n    sum by (kubernetes_io_hostname) (kubelet_running_pods),\n    \"node\",\n    \"$1\",\n    \"kubernetes_io_hostname\",\n    \"(.+)\"\n  )\n)"
    }
   ]
  },
  {
   "title": "Nodes not ready for more than 10 minutes",
   "type": "graph",
   "description": "Shows the number of node that are in the NotReady state for more than 10 minutes du to the kubelet not responding",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Node count" }
   ],
   "targets": [
    {
     "expr": "count_over_time(\n  sum by (node, type)(last_over_time(kube_node_status_condition{condition=\"Ready\",status!=\"true\"}[1m]) == 1)[10m:1m]\n) >= 10",
     "legendFormat": "{{label_worker_gardener_cloud_pool}}"
    }
   ]
  },
  {
   "title": "Node Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed Connection Tracking Inserts",
     "type": "graph",
     "description": "Shows the amount of failed inserts into the connection tracking table (conntrack). Should be close to zero.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_nf_conntrack_stat_insert_failed[$__rate_interval])) by (node)",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}