{
 "title": "Seed Overload",
 "tags": [
  "seed",
  "controlplane",
  "apiserver-details",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Api-server  Overload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"kube-apiserver.*\"}) / 1024^3"
    }
   ]
  },
  { "title": "ETCD Overload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"etcd-main.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"etcd-main.*\"}[$__rate_interval])) + sum(rate(container_network_receive_bytes_total{pod=~\"etcd-main.*\"}[$__rate_interval])) "
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{role=\"main\"}",
     "legendFormat": "{{pod}} DB Size"
    }
   ]
  },
  {
   "title": "Cloud-controller-manager Overload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  },
  { "title": "Nodes Overload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Number of Nodes in Worker Group(s) All",
   "type": "gauge",
   "description": "Shows the number of nodes of selected worker groups in the cluster over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{label_worker_gardener_cloud_pool=~\"All\"})"
    }
   ]
  },
  {
   "title": "Resource Quotas Overload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true
  }
 ]
}