apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    service.alpha.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    networking.resources.gardener.cloud/from-world-to-ports: '[{"port":8132,"protocol":"TCP"},{"port":8443,"protocol":"TCP"},{"port":9443,"protocol":"TCP"}]'
    networking.resources.gardener.cloud/namespace-selectors: '[{"matchLabels":{"gardener.cloud/role":"shoot"}}]'
    networking.resources.gardener.cloud/pod-label-selector-namespace-alias: all-istio-ingresses
{{- if .Values.annotations }}
{{ .Values.annotations | toYaml | indent 4 }}
{{- end }}
  labels:
    app.kubernetes.io/version: {{ .Values.ingressVersion }}
{{ .Values.labels | toYaml | indent 4 }}
spec:
  type: {{ .Values.serviceType }}
  selector:
{{ .Values.labels  | toYaml | indent 4 }}
  ports:
{{- if .Values.ports }}
{{ toYaml .Values.ports | indent 2 }}
{{- end }}
{{- if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
{{- end }}
{{- if .Values.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.externalTrafficPolicy }}
{{- end }}
