apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-local-setup
  labels: {component: remote-local-setup}
spec:
  selector:
    matchLabels: {component: remote-local-setup}
  strategy: {type: Recreate}
  template:
    metadata:
      labels: {component: remote-local-setup}
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: dev
        image: docker:20.10-dind
        command:
        - /bin/sh
        - -c
        - |
          set -ex
          cd
          apk add bash bash-completion curl fzf gcompat git jq less lsof make mandoc mc parallel procps sed strace tar tmux tmux-doc yq vim go
          apk add --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main mount
          apk add --repository=http://dl-cdn.alpinelinux.org/alpine/edge/k9s k9s
          echo golang            && curl -sLO "https://go.dev/dl/$(curl -sL https://golang.org/VERSION?m=text).linux-amd64.tar.gz" && tar -C /usr/local -xzf go1.*.linux-amd64.tar.gz
          echo helm              && curl -sLO "https://get.helm.sh/helm-$(curl -sL https://api.github.com/repos/helm/helm/releases/latest | jq .tag_name -r)-linux-amd64.tar.gz" && tar -xzf helm-*-linux-amd64.tar.gz && mv linux-amd64/helm /usr/local/bin/helm
          echo kind              && curl -sL  "https://kind.sigs.k8s.io/dl/$(curl -sL https://api.github.com/repos/kubernetes-sigs/kind/releases/latest | jq .tag_name -r)/kind-linux-amd64" -o /usr/local/bin/kind && chmod +x /usr/local/bin/kind
          echo kns               && curl -sL  "https://raw.githubusercontent.com/blendle/kns/master/bin/kns" -o /usr/local/bin/kns && chmod +x /usr/local/bin/kns
          echo ktx               && curl -sL  "https://raw.githubusercontent.com/blendle/kns/master/bin/ktx" -o /usr/local/bin/ktx && chmod +x /usr/local/bin/ktx
          echo kube-ps1          && curl -sL  "https://raw.githubusercontent.com/jonmosco/kube-ps1/master/kube-ps1.sh" -o ~/.kube-ps1.sh
          echo kubectl           && curl -sL  "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl && chmod +x /usr/local/bin/kubectl
          echo tmux-completion   && curl -sL  "https://raw.githubusercontent.com/imomaliev/tmux-bash-completion/master/completions/tmux" -o /usr/share/bash-completion/completions/tmux
          echo docker-completion && curl -sL  "https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker" -o /usr/share/bash-completion/completions/docker
          echo yaml2json         && curl -sL  "https://github.com/bronze1man/yaml2json/releases/download/$(curl -sL https://api.github.com/repos/bronze1man/yaml2json/releases/latest | jq .tag_name -r)/yaml2json_linux_amd64" -o /usr/local/bin/yaml2json && chmod +x /usr/local/bin/yaml2json
          echo '127.0.0.1 api.local.local.external.local.gardener.cloud' >> /etc/hosts
          echo 'source ~/.bashrc' > ~/.bash_profile
          cat > ~/.bashrc <<"EOF"
            export GOPATH=~/go
            export PATH=$PATH:/usr/local/go/bin
            export KUBECONFIG=~/gardener/example/gardener-local/kind/local/kubeconfig:/tmp/kubeconfig-shoot-local.yaml
            source <(kubectl completion bash)
            alias k=kubectl
            complete -o default -F __start_kubectl k
            source ~/.kube-ps1.sh
            export PS1='[\w $(printf "$(kube_ps1)")]\$ '
            export TERM=xterm-256color
            cd ~/gardener
            echo -e "\e[1;33mTo attach to the \e[1;36mgardener\e[1;33m tmux session, run '\e[1;32mtmux attach -t gardener\e[1;33m'\e[0m"
          EOF
          cat > ~/.tmux.conf <<"EOF"
            set -g mouse on
            set -g mode-keys vi
            set -g default-shell /bin/bash
            set -g pane-border-status top
            set -g pane-border-format " #{pane_index} #{pane_title} - #{pane_current_command} "
          EOF
          git clone -q https://github.com/gardener/gardener.git
          cd gardener
          mkdir -p ~/go/src/github.com/gardener
          ln -s ~/gardener ~/go/src/github.com/gardener/gardener
          ln -s ~/gardener/hack/tools/bin/protoc-gen-gogo ~/gardener/protoc-gen-gogo
          # TODO 'host.docker.internal' can not be resolved on docker for Linux (https://github.com/docker/for-linux/issues/264, https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal)
          #      maybe there is a better way than using the IP address of the docker0 device: 172.17.0.1
          #      ip addr show docker0 | awk '/inet .* docker0/{print substr($2,0, index($2,"/")-1)}'
          git grep -l host.docker.internal | xargs sed -i 's/host.docker.internal/172.17.0.1/'
          dockerd-entrypoint.sh &
          until docker ps >/dev/null 2>&1; do sleep 1; done
          tmux new -d -s gardener -n gardener1
          tmux select-pane -T top
          tmux send top Enter; sleep 1; tmux send 1; sleep 1; tmux send C; sleep 1; tmux send i; sleep 1; tmux send t; sleep 1; tmux send V; sleep 1; tmux send s; sleep 1; tmux send 5 Enter
          function step {
            tmux split-window \; select-pane -T "$1"
            sleep 1
            tmux send "$2"
            tmux select-layout even-vertical
          }
          step kind            "make kind-up   KIND_ENV=local"
          step dev-setup       "make dev-setup"
          step gapi            "kubectl wait --for=condition=ready pod -l run=etcd -n garden                  && make start-apiserver"
          step gac             "kubectl wait --for=condition=available apiservice v1beta1.core.gardener.cloud && make start-admission-controller"
          step dev-setup-hooks "make dev-setup DEV_SETUP_WITH_WEBHOOKS=true"
          tmux new-window -n gardener2
          tmux select-pane -T "gcm"; sleep 1; tmux send "make start-controller-manager"
          step local           "make register-local-env"
          step gardenlet       "make start-gardenlet SEED_NAME=local"
          # TODO avoid workarounds
          step local           'KUBECONFIG=${KUBECONFIG%:*} USER=root make start-extension-provider-local'
          step shoot           "kubectl apply -f example/provider-local/shoot.yaml"
          step shoot           "kubectl -n garden-local get secret local.kubeconfig -o jsonpath={.data.kubeconfig} | base64 -d > /tmp/kubeconfig-shoot-local.yaml"
          touch /tmp/ready
          read
        stdin: true
        startupProbe:
          exec:
            command:
            - cat
            - /tmp/ready
          failureThreshold: 30
          periodSeconds: 10
        resources:
          requests: {cpu: 8, memory: 16G}
          limits:   {cpu: 8, memory: 16G}
        securityContext:
          privileged: true
        volumeMounts:
        # Without bind mounting `/sys/fs/cgroup` the shoot worker node fails currently; all the other components work fine
        # Due to bind mounting `/sys/fs/cgroup` from the host, the docker container in this dind pod (i.e. the KinD cluster) uses a top level cgroup and hence is not constrained by the resource limits of this pod
        # These host cgroups might leak, but it is probably not an issue e.g. due to hibernating the hosting Gardener dev k8s cluster so that the nodes are recreated regularly anyway
        # To avoid conflicts on the top level docker cgroup, one dev pod per node is recommended
        # See
        # https://github.com/kubernetes-sigs/kind/issues/303
        # https://github.com/kubernetes/test-infra/blob/dcf27e157932c3e8680be4ae6cb8a4e2c7acf8cf/config/prow/config.yaml#L978-L988
        # https://github.com/gardener/ci-infra/blob/dff565bced0f386dd1acb0743beb3831dae6c10d/config/prow/config.yaml#L288-L298
        - {name: cgroup,  mountPath: /sys/fs/cgroup}
        - {name: modules, mountPath: /lib/modules, readOnly: true}
      volumes:
      - {name: cgroup,  hostPath: {type: Directory, path: /sys/fs/cgroup}}
      - {name: modules, hostPath: {type: Directory, path: /lib/modules}}
