# TODO(oliver-goetz): Delete this Helm chart in a future version.
apiVersion: v1
kind: Service
metadata:
  name: apiserver-proxy
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
