apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: istiod
  namespace: {{ .Release.Namespace }}
{{- if .Values.ignoreMode }}
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}
  labels:
{{ .Values.labels | toYaml | indent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istiod
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: discovery
        minAllowed:
          memory: 128Mi
