apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
{{- if .Values.ignoreMode }}
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}
spec:
  host: "*"
  exportTo:
  - "*"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
