{{- if .Values.deployNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
{{- if .Values.ignoreMode }}
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
    gardener.cloud/role: istio-system
{{ end -}}
