apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod
  namespace: {{ .Release.Namespace }}
{{- if .Values.ignoreMode }}
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}
  labels:
{{ .Values.labels | toYaml | indent 4 }}
automountServiceAccountToken: false
