apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.resources.gardener.cloud/from-world-to-ports: '[{"port":{{ .Values.ports.https }},"protocol":"TCP"}]'
    networking.resources.gardener.cloud/namespace-selectors: '[{"matchLabels":{"gardener.cloud/role":"istio-ingress"}},{"matchExpressions":[{"key":"handler.exposureclass.gardener.cloud/name","operator":"Exists"}]}]'
{{- if .Values.ignoreMode }}
    resources.gardener.cloud/mode: Ignore
{{- end }}
  labels:
{{ .Values.labels | toYaml | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: https-sds # mTLS with k8s-signed cert
    port: 15012
    protocol: TCP
  - name: https-webhook # validation and injection
    port: 443
    protocol: TCP
    targetPort: {{ .Values.ports.https }}
  - name: {{ .Values.portsNames.metrics }} # prometheus metrics
    port: 15014
    protocol: TCP
    targetPort: 15014
  selector:
{{ .Values.labels | toYaml | indent 4 }}
