apiVersion: {{ include "networkpolicyversion" . }}
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Ingress to the Grafana from the nginx controller and Egress to Prometheus.
  namespace: {{ .Release.Namespace }}
  name: allow-grafana
spec:
  podSelector:
    matchLabels:
      component: grafana
      gardener.cloud/role: monitoring
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          role: garden
      podSelector:
        matchLabels:
          app: nginx-ingress
          component: controller
    ports:
    - protocol: TCP
      port: {{ required ".ports.grafana is required" .Values.ports.grafana }}
  policyTypes:
  - Egress
  - Ingress
