{{- if .Values.coredns.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: gardener-extension-provider-local-coredns
  annotations:
    "resources.gardener.cloud/ignore": "true"
data:
  changeme.override: "# checkout the docs on how to use: https://github.com/gardener/gardener/blob/master/docs/usage/custom-dns-config.md"
{{- end -}}
