# TODO(oliver-goetz): Delete this Helm chart in a future version.
{{- if not .Values.global.pspDisabled }}
apiVersion: {{ include "rbacversion" . }}
kind: RoleBinding
metadata:
  name: gardener.cloud:psp:apiserver-proxy
  namespace: kube-system
  annotations:
    resources.gardener.cloud/mode: Ignore
{{- end }}
