gardener:
  seed:
    istio:
      # Add one 'global' address and one per zone, see https://github.com/gardener/gardener/pull/6997
      listenAddresses:
      - 127.0.0.1
      - 127.0.0.10
      - 127.0.0.11
      - 127.0.0.12

registry:
  hostname: gardener-local-ha-multi-zone-control-plane

workers:
- zone: "1"
- zone: "2"
