apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-provisioner
rules:
- apiGroups:
    - ""
  resources:
    - nodes
    - persistentvolumeclaims
    - configmaps
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - endpoints
    - persistentvolumes
    - pods
  verbs:
    - '*'
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - storage.k8s.io
  resources:
    - storageclasses
  verbs:
    - get
    - list
    - watch
{{- if not .Values.pspDisabled }}
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - gardener.kube-system.local-path-provisioner
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end }}
