---
apiVersion: operator.config.gardener.cloud/v1alpha1
kind: OperatorConfiguration
runtimeClientConnection:
  qps: 100
  burst: 130
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
  resourceLock: leases
  resourceNamespace: garden
  resourceName: gardener-operator-leader-election
logLevel: info
logFormat: text
server:
  webhooks:
    bindAddress: 0.0.0.0
    port: 2750
  healthProbes:
    bindAddress: 0.0.0.0
    port: 2751
  metrics:
    bindAddress: 0.0.0.0
    port: 2752
debugging:
  enableProfiling: false
  enableContentionProfiling: false
featureGates:
  DefaultSeccompProfile: true
  HVPA: true
controllers:
  garden:
    concurrentSyncs: 1
    syncPeriod: 1h
    etcdConfig:
      etcdController:
        workers: 3
      custodianController:
        workers: 3
      backupCompactionController:
        workers: 3
        enableBackupCompaction: false
        eventsThreshold: 1000000
        activeDeadlineDuration: "3h"
    # backupLeaderElection:
    #   reelectionPeriod: 5s
    #   etcdConnectionTimeout: 5s
